In [1]:
import pandas as pd
import numpy as np
from matplotlib import rc
from matplotlib import pyplot as plt
import seaborn as sns
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)
import warnings
warnings.filterwarnings('ignore')

rc('font', family='AppleGothic')

plt.rcParams['axes.unicode_minus'] = False

In [2]:
df = pd.read_csv("../GP_전처리완료/GP_통합(3years)_ver2_취업예측용.csv")

In [3]:
cols = df.columns

In [4]:
encoding_ls = []
no_encoding_ls = []

for col in cols:
    if df[col].value_counts().index.__len__() <=17:
        encoding_ls.append(col)
    else :
        no_encoding_ls.append(col)

print(encoding_ls, encoding_ls.__len__())
print()
print(no_encoding_ls, no_encoding_ls.__len__())

['연도', '본분교', '국공사립', '학위과정유형', '주야간', '전공계열', '학교유형', '학교소재지역', '성별', '혼인여부 및 배우자 학력', '아버지 학력', '어머니 학력', '부모님 소득', '부모님 자산', '대학 입학 구분', '진로 선택 및 취업준비 프로그램 참여 횟수', '휴학 횟수', '석사/박사 재학여부', '목표 직업', '목표 직업 유형', '근로소득', '근로시간', '적성 및 흥미', '전공 관련성', '업무 난이도', '업무량', '개인 발전 가능성', '직업 미래 전망', '고용 안정성', '근무환경', '복리후생', '회사 규모', '출퇴근 거리', '일자리의 사회적 평판', '업무의 사회적 평판', '합격 제의 횟수', '거절 이유', '구직 과정 어려운 점', '종사상 지위', '인턴경험여부(현직장)', '구직경로', '구직방법', '취업_중요요소_1순위', '취업_중요요소_2순위', '건강한정도', '흡연여부', '음주빈도', '재학중 일자리 경험', '고용형태', '연수횟수', '토스등급', '오픽점수', '탭스', '취업여부'] 54

['전공_소분류_코드', '전공_세분류_코드', '연령', '가정의 경제적 지원', 'GPA', '학자금대출 금액', '희망연봉', '구직기간', '일자리 지원 횟수', '면접 횟수', '구직기간(주)', '운동시간(주)', '수면시간(일)', '일자리 횟수', '교육훈련횟수', '시간총합', '토익', '토플ibt', '체류시간'] 19


In [5]:
encoding_ls = encoding_ls[1:-1] # 연도와 취업여부 제외
print(encoding_ls.__len__())

52


In [6]:
encoding_ls.remove('진로 선택 및 취업준비 프로그램 참여 횟수')
encoding_ls.remove('휴학 횟수')
encoding_ls.remove('합격 제의 횟수')
encoding_ls.remove('연수횟수')
encoding_ls.remove('종사상 지위')

print(encoding_ls.__len__())


47


In [7]:
for col in encoding_ls:
    print(df[col].value_counts())

1    48967
3     1622
2     1101
Name: 본분교, dtype: int64
3    39129
1    11066
2      662
4      626
6      148
5       59
Name: 국공사립, dtype: int64
3    49865
5      918
2      494
1      287
6       97
4       28
7        1
Name: 학위과정유형, dtype: int64
1    48657
2     3019
3       14
Name: 주야간, dtype: int64
4    14819
2    10890
5     6921
1     6195
7     5613
3     3647
6     3605
Name: 전공계열, dtype: int64
2    39189
1    11887
3      614
Name: 학교유형, dtype: int64
1     11321
8      7683
2      4823
14     3879
11     3257
15     2614
4      2567
12     2504
9      2351
10     2226
3      2206
6      2015
13     1400
5      1325
7       618
17      483
16      418
Name: 학교소재지역, dtype: int64
1    28004
2    23686
Name: 성별, dtype: int64
0    49201
6     1284
4      515
5      455
7      166
3       56
2       12
1        1
Name: 혼인여부 및 배우자 학력, dtype: int64
4    20737
6    17839
7     4239
5     3774
3     2811
2     1989
1      301
Name: 아버지 학력, dtype: int64
4    27921
6    12678
5     3

In [8]:
encoding_ls

['본분교',
 '국공사립',
 '학위과정유형',
 '주야간',
 '전공계열',
 '학교유형',
 '학교소재지역',
 '성별',
 '혼인여부 및 배우자 학력',
 '아버지 학력',
 '어머니 학력',
 '부모님 소득',
 '부모님 자산',
 '대학 입학 구분',
 '석사/박사 재학여부',
 '목표 직업',
 '목표 직업 유형',
 '근로소득',
 '근로시간',
 '적성 및 흥미',
 '전공 관련성',
 '업무 난이도',
 '업무량',
 '개인 발전 가능성',
 '직업 미래 전망',
 '고용 안정성',
 '근무환경',
 '복리후생',
 '회사 규모',
 '출퇴근 거리',
 '일자리의 사회적 평판',
 '업무의 사회적 평판',
 '거절 이유',
 '구직 과정 어려운 점',
 '인턴경험여부(현직장)',
 '구직경로',
 '구직방법',
 '취업_중요요소_1순위',
 '취업_중요요소_2순위',
 '건강한정도',
 '흡연여부',
 '음주빈도',
 '재학중 일자리 경험',
 '고용형태',
 '토스등급',
 '오픽점수',
 '탭스']

In [9]:
no_encoding_ls = list(cols)

In [10]:
for i in encoding_ls:
    no_encoding_ls.remove(i)
no_encoding_ls

['연도',
 '전공_소분류_코드',
 '전공_세분류_코드',
 '연령',
 '가정의 경제적 지원',
 '진로 선택 및 취업준비 프로그램 참여 횟수',
 'GPA',
 '학자금대출 금액',
 '휴학 횟수',
 '희망연봉',
 '구직기간',
 '일자리 지원 횟수',
 '면접 횟수',
 '합격 제의 횟수',
 '종사상 지위',
 '구직기간(주)',
 '운동시간(주)',
 '수면시간(일)',
 '일자리 횟수',
 '교육훈련횟수',
 '시간총합',
 '연수횟수',
 '토익',
 '토플ibt',
 '체류시간',
 '취업여부']

In [11]:
all_dum_df = df[no_encoding_ls]
all_dum_df

연도  전공_소분류_코드  전공_세분류_코드  연령  가정의 경제적 지원  진로 선택 및 취업준비 프로그램 참여 횟수  \
0      2018          0          7  23           0                        3   
1      2018          0          4  21           0                        7   
2      2018          0          4  21          40                        2   
3      2018          0          2  25           0                        1   
4      2018          0          2  21           0                        3   
...     ...        ...        ...  ..         ...                      ...   
51685  2016        205       5025  27           0                        0   
51686  2016        205       5028  50           0                        0   
51687  2016        205       5028  26           0                        0   
51688  2016        205       5030  27           0                        0   
51689  2016        205       5031  25           0                        0   

         GPA  학자금대출 금액  휴학 횟수  희망연봉  ...  운동시간(주)  수면시간(일)  일자리 횟수  교육훈련횟수  \
0      73.33         0      0  2000  ...        5       10       1       0   
1      66.67         0      0  2400  ...       12        8       0       1   
2      95.56         0      0  2000  ...        2        8       0       0   
3      84.44         0      1  3600  ...        1        4       0       0   
4      91.11         0      0  2200  ...        3        8       2       0   
...      ...       ...    ...   ...  ...      ...      ...     ...     ...   
51685  95.56       500      1  3000  ...        2        6       0       0   
51686  80.00      2800      0  3000  ...        2        5       0       0   
51687  44.44         0      0  2400  ...        7        5       1       0   
51688  73.33         0      1  3000  ...        4        6       1       0   
51689  86.67         0      1  3000  ...        0        5       0       0   

       시간총합  연수횟수   토익  토플ibt  체류시간  취업여부  
0         0     0    0      0     0     1  
1       240     0    0      0     0     0  
2         0     0  800      0     0     1  
3         0     1    0      0    12     1  
4         0     0    0      0     0     1  
...     ...   ...  ...    ...   ...   ...  
51685     0     0    0      0     0     1  
51686     0     0    0      0     0     1  
51687     0     1    0      0    10     1  
51688     0     0    0      0     0     1  
51689     0     0    0      0     0     1  

[51690 rows x 26 columns]

In [12]:
from tqdm import tqdm

In [13]:
for encode in tqdm(encoding_ls):
    dummy_df = pd.get_dummies(df[encode])
    col_ls = []
    for col in dummy_df.columns:
        col_ls.append(encode+'_'+str(col))
    dummy_df.columns = col_ls
    all_dum_df = pd.concat([all_dum_df, dummy_df], axis=1)

100%|██████████| 47/47 [00:00<00:00, 248.73it/s]


In [14]:
all_dum_df

연도  전공_소분류_코드  전공_세분류_코드  연령  가정의 경제적 지원  진로 선택 및 취업준비 프로그램 참여 횟수  \
0      2018          0          7  23           0                        3   
1      2018          0          4  21           0                        7   
2      2018          0          4  21          40                        2   
3      2018          0          2  25           0                        1   
4      2018          0          2  21           0                        3   
...     ...        ...        ...  ..         ...                      ...   
51685  2016        205       5025  27           0                        0   
51686  2016        205       5028  50           0                        0   
51687  2016        205       5028  26           0                        0   
51688  2016        205       5030  27           0                        0   
51689  2016        205       5031  25           0                        0   

         GPA  학자금대출 금액  휴학 횟수  희망연봉  ...  탭스_1  탭스_2  탭스_3  탭스_4  탭스_5  탭스_6  \
0      73.33         0      0  2000  ...     0     0     0     0     0     0   
1      66.67         0      0  2400  ...     0     0     0     0     0     0   
2      95.56         0      0  2000  ...     0     0     0     0     0     0   
3      84.44         0      1  3600  ...     0     0     0     0     0     0   
4      91.11         0      0  2200  ...     0     0     0     0     0     0   
...      ...       ...    ...   ...  ...   ...   ...   ...   ...   ...   ...   
51685  95.56       500      1  3000  ...     0     0     0     0     0     0   
51686  80.00      2800      0  3000  ...     0     0     0     0     0     0   
51687  44.44         0      0  2400  ...     0     0     0     0     0     0   
51688  73.33         0      1  3000  ...     0     0     0     0     0     0   
51689  86.67         0      1  3000  ...     0     0     0     0     0     0   

       탭스_7  탭스_8  탭스_9  탭스_10  
0         0     0     0      0  
1         0     0     0      0  
2         0     0     0      0  
3         0     0     0      0  
4         0     0     0      0  
...     ...   ...   ...    ...  
51685     0     0     0      0  
51686     0     0     0      0  
51687     0     0     0      0  
51688     0     0     0      0  
51689     0     0     0      0  

[51690 rows x 361 columns]

In [121]:
df_new = pd.read_csv("../GP_전처리완료/GP_통합(3years)_ver5_원핫_취업예측용.csv")

In [15]:
X_ls = list(all_dum_df.columns)

In [16]:
X_ls.remove('연도')
X_ls.remove('전공_소분류_코드')
X_ls.remove('전공_세분류_코드')
X_ls.remove('취업여부')

In [17]:
X_ls

['연령',
 '가정의 경제적 지원',
 '진로 선택 및 취업준비 프로그램 참여 횟수',
 'GPA',
 '학자금대출 금액',
 '휴학 횟수',
 '희망연봉',
 '구직기간',
 '일자리 지원 횟수',
 '면접 횟수',
 '합격 제의 횟수',
 '종사상 지위',
 '구직기간(주)',
 '운동시간(주)',
 '수면시간(일)',
 '일자리 횟수',
 '교육훈련횟수',
 '시간총합',
 '연수횟수',
 '토익',
 '토플ibt',
 '체류시간',
 '본분교_1',
 '본분교_2',
 '본분교_3',
 '국공사립_1',
 '국공사립_2',
 '국공사립_3',
 '국공사립_4',
 '국공사립_5',
 '국공사립_6',
 '학위과정유형_1',
 '학위과정유형_2',
 '학위과정유형_3',
 '학위과정유형_4',
 '학위과정유형_5',
 '학위과정유형_6',
 '학위과정유형_7',
 '주야간_1',
 '주야간_2',
 '주야간_3',
 '전공계열_1',
 '전공계열_2',
 '전공계열_3',
 '전공계열_4',
 '전공계열_5',
 '전공계열_6',
 '전공계열_7',
 '학교유형_1',
 '학교유형_2',
 '학교유형_3',
 '학교소재지역_1',
 '학교소재지역_2',
 '학교소재지역_3',
 '학교소재지역_4',
 '학교소재지역_5',
 '학교소재지역_6',
 '학교소재지역_7',
 '학교소재지역_8',
 '학교소재지역_9',
 '학교소재지역_10',
 '학교소재지역_11',
 '학교소재지역_12',
 '학교소재지역_13',
 '학교소재지역_14',
 '학교소재지역_15',
 '학교소재지역_16',
 '학교소재지역_17',
 '성별_1',
 '성별_2',
 '혼인여부 및 배우자 학력_0',
 '혼인여부 및 배우자 학력_1',
 '혼인여부 및 배우자 학력_2',
 '혼인여부 및 배우자 학력_3',
 '혼인여부 및 배우자 학력_4',
 '혼인여부 및 배우자 학력_5',
 '혼인여부 및 배우자 학력_6',
 '혼인여부 및 배우자 학력_7',
 '아버지 학력_1',
 '아버

In [18]:
X = all_dum_df[X_ls]
y = all_dum_df['취업여부']

In [126]:
for col in df_new.columns:
    print(col)

연도
연령
가정의 경제적 지원
진로 선택 및 취업준비 프로그램 참여 횟수
GPA
학자금대출 금액
휴학 횟수
희망연봉
구직기간
일자리 지원 횟수
면접 횟수
합격 제의 횟수
구직기간(주)
운동시간(주)
수면시간(일)
음주빈도
일자리 횟수
교육훈련횟수
시간총합
연수횟수
토익
토플ibt
체류시간
취업여부
기업 구분
종사상 지위
본분교_1
본분교_2
본분교_3
국공사립_1
국공사립_2
국공사립_3
국공사립_4
국공사립_5
국공사립_6
학위과정유형_1
학위과정유형_2
학위과정유형_3
학위과정유형_4
학위과정유형_5
학위과정유형_6
학위과정유형_7
주야간_1
주야간_2
주야간_3
전공계열_1
전공계열_2
전공계열_3
전공계열_4
전공계열_5
전공계열_6
전공계열_7
전공_소분류_코드_0
전공_소분류_코드_1
전공_소분류_코드_2
전공_소분류_코드_3
전공_소분류_코드_4
전공_소분류_코드_5
전공_소분류_코드_6
전공_소분류_코드_7
전공_소분류_코드_8
전공_소분류_코드_9
전공_소분류_코드_10
전공_소분류_코드_11
전공_소분류_코드_12
전공_소분류_코드_13
전공_소분류_코드_14
전공_소분류_코드_15
전공_소분류_코드_16
전공_소분류_코드_17
전공_소분류_코드_18
전공_소분류_코드_19
전공_소분류_코드_20
전공_소분류_코드_21
전공_소분류_코드_22
전공_소분류_코드_23
전공_소분류_코드_24
전공_소분류_코드_25
전공_소분류_코드_26
전공_소분류_코드_27
전공_소분류_코드_28
전공_소분류_코드_29
전공_소분류_코드_30
전공_소분류_코드_31
전공_소분류_코드_32
전공_소분류_코드_33
전공_소분류_코드_34
전공_소분류_코드_35
전공_소분류_코드_36
전공_소분류_코드_37
전공_소분류_코드_38
전공_소분류_코드_39
전공_소분류_코드_40
전공_소분류_코드_41
전공_소분류_코드_42
전공_소분류_코드_43
전공_소분류_코드_44
전공_소분류_코드_45
전공_소분류_코드_46
전공_소분류_코드_47
전공_소분류_코드_48
전공_

In [124]:
X_new = df_new.drop(['취업여부','연도'], axis=1)
y_new = df_new['취업여부']

In [100]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

### 로지스틱 회귀와 KNN 기반 (소프트) 보팅

In [107]:
def voting_lr_knn(X_train, X_test, y_train, y_test, voting='soft', print_all=True):
    lr_clf = LogisticRegression()
    knn_clf = KNeighborsClassifier()
    vo_clf = VotingClassifier(estimators = [('LR', lr_clf), ('KNN', knn_clf)], voting=voting)

    classifiers = [vo_clf, lr_clf, knn_clf]

    if print_all:
        clf_ls = []
        for classifier in classifiers:
            classifier.fit(X_train, y_train)
            pred = classifier.predict(X_test)
            print(classifier.__class__.__name__, '정확도 :', accuracy_score(y_test, pred))
            print(classifier.__class__.__name__, '정밀도 :', precision_score(y_test, pred))
            print(classifier.__class__.__name__, '재현율 :', recall_score(y_test, pred))
            print(classifier.__class__.__name__, '오차 행렬 :\n', confusion_matrix(y_test, pred))
            print()
    else:
        return vo_clf

In [108]:
def Skfold_voting_lr_knn(X, y, n_splits=5, voting='soft'):

    st_kfold = StratifiedKFold(n_splits = n_splits)

    cv_acc, cv_pre, cv_recall = [], [], []

    n = 1
    for train_idx , val_idx in st_kfold.split(X , y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[val_idx]
        y_train = y.iloc[train_idx]
        y_test = y.iloc[val_idx]
        
        vo_clf = voting_lr_knn(X_train, X_test, y_train, y_test, voting=voting, print_all=False)
        vo_clf.fit(X_train , y_train)
        pred = vo_clf.predict(X_test)
        acc = np.round(accuracy_score(y_test , pred), 3)
        pre = np.round(precision_score(y_test, pred), 3)
        recall = np.round(recall_score(y_test, pred), 3)
        matrix = confusion_matrix(y_test, pred)
        
        print(f'[교차검증 : {n}회]')
        print(f'{n}회 교차검증의 정확도 : {acc}')
        print(f'{n}회 교차검증의 정밀도 : {pre}')
        print(f'{n}회 교차검증의 재현율 : {recall}')
        print(f'{n}회 교차검증의 오차행렬 : \n{matrix} \n')
        
        n+=1

        cv_acc.append(acc)
        cv_pre.append(pre)
        cv_recall.append(recall)


    print('평균 정확도' , np.round( np.mean(cv_acc),2))
    print('평균 정밀도' , np.round( np.mean(cv_pre),2))
    print('평균 재현율' , np.round( np.mean(cv_recall),2))

In [109]:
Skfold_voting_lr_knn(X, y)

[교차검증 : 1회]
1회 교차검증의 정확도 : 0.973
1회 교차검증의 정밀도 : 0.974
1회 교차검증의 재현율 : 0.991
1회 교차검증의 오차행렬 : 
[[2186  213]
 [  68 7871]] 

[교차검증 : 2회]
2회 교차검증의 정확도 : 0.975
2회 교차검증의 정밀도 : 0.974
2회 교차검증의 재현율 : 0.993
2회 교차검증의 오차행렬 : 
[[2192  208]
 [  55 7883]] 

[교차검증 : 3회]
3회 교차검증의 정확도 : 0.973
3회 교차검증의 정밀도 : 0.972
3회 교차검증의 재현율 : 0.993
3회 교차검증의 오차행렬 : 
[[2170  230]
 [  54 7884]] 

[교차검증 : 4회]
4회 교차검증의 정확도 : 0.968
4회 교차검증의 정밀도 : 0.964
4회 교차검증의 재현율 : 0.995
4회 교차검증의 오차행렬 : 
[[2105  295]
 [  36 7902]] 

[교차검증 : 5회]
5회 교차검증의 정확도 : 0.971
5회 교차검증의 정밀도 : 0.968
5회 교차검증의 재현율 : 0.995
5회 교차검증의 오차행렬 : 
[[2140  260]
 [  40 7898]] 

평균 정확도 0.97
평균 정밀도 0.97
평균 재현율 0.99


In [125]:
Skfold_voting_lr_knn(X_new, y_new)

[교차검증 : 1회]
1회 교차검증의 정확도 : 0.977
1회 교차검증의 정밀도 : 0.978
1회 교차검증의 재현율 : 0.992
1회 교차검증의 오차행렬 : 
[[2220  179]
 [  63 7876]] 

[교차검증 : 2회]
2회 교차검증의 정확도 : 0.977
2회 교차검증의 정밀도 : 0.976
2회 교차검증의 재현율 : 0.995
2회 교차검증의 오차행렬 : 
[[2204  196]
 [  43 7895]] 



KeyboardInterrupt: 

### 로지스틱 회귀와 의사결정 나무 기반 (소프트) 보팅

In [110]:
def voting_lr_dt(X_train, X_test, y_train, y_test, voting='soft', print_all=True):
    lr_clf = LogisticRegression()
    dt_clf = DecisionTreeClassifier()
    vo_clf = VotingClassifier(estimators = [('LR', lr_clf), ('DT', dt_clf)], voting=voting)

    classifiers = [vo_clf, lr_clf, dt_clf]

    if print_all:
        for classifier in classifiers:
            classifier.fit(X_train, y_train)
            pred = classifier.predict(X_test)
            print(classifier.__class__.__name__, '정확도 :', accuracy_score(y_test, pred))
            print(classifier.__class__.__name__, '정밀도 :', precision_score(y_test, pred))
            print(classifier.__class__.__name__, '재현율 :', recall_score(y_test, pred))
            print(classifier.__class__.__name__, '오차 행렬 :\n', confusion_matrix(y_test, pred))
            print()
    else:
        return vo_clf

In [113]:
def Skfold_voting_lr_dt(X, y, n_splits=5, voting='soft', test_size=0.3):

    st_kfold = StratifiedKFold(n_splits = n_splits)

    cv_acc, cv_pre, cv_recall = [], [], []

    n = 1
    for train_idx , val_idx in st_kfold.split(X , y):
        
        X_train = X.iloc[train_idx]
        X_test = X.iloc[val_idx]
        y_train = y.iloc[train_idx]
        y_test = y.iloc[val_idx]
        
        vo_clf = voting_lr_dt(X_train, X_test, y_train, y_test, voting=voting, print_all=False)
        vo_clf.fit(X_train , y_train)
        pred = vo_clf.predict(X_test)
        acc = np.round(accuracy_score(y_test , pred), 3)
        pre = np.round(precision_score(y_test, pred), 3)
        recall = np.round(recall_score(y_test, pred), 3)
        matrix = confusion_matrix(y_test, pred)
        
        print(f'[교차검증 : {n}회]')
        print(f'{n}회 교차검증의 정확도 : {acc}')
        print(f'{n}회 교차검증의 정밀도 : {pre}')
        print(f'{n}회 교차검증의 재현율 : {recall}')
        print(f'{n}회 교차검증의 오차행렬 : \n{matrix} \n')
        
        n+=1

        cv_acc.append(acc)
        cv_pre.append(pre)
        cv_recall.append(recall)


    print('평균 정확도' , np.round( np.mean(cv_acc),2))
    print('평균 정밀도' , np.round( np.mean(cv_pre),2))
    print('평균 재현율' , np.round( np.mean(cv_recall),2))

In [114]:
Skfold_voting_lr_dt(X, y)

[교차검증 : 1회]
1회 교차검증의 정확도 : 1.0
1회 교차검증의 정밀도 : 1.0
1회 교차검증의 재현율 : 1.0
1회 교차검증의 오차행렬 : 
[[2399    0]
 [   0 7939]] 

[교차검증 : 2회]
2회 교차검증의 정확도 : 1.0
2회 교차검증의 정밀도 : 1.0
2회 교차검증의 재현율 : 1.0
2회 교차검증의 오차행렬 : 
[[2400    0]
 [   0 7938]] 

[교차검증 : 3회]
3회 교차검증의 정확도 : 1.0
3회 교차검증의 정밀도 : 1.0
3회 교차검증의 재현율 : 1.0
3회 교차검증의 오차행렬 : 
[[2400    0]
 [   0 7938]] 

[교차검증 : 4회]
4회 교차검증의 정확도 : 1.0
4회 교차검증의 정밀도 : 1.0
4회 교차검증의 재현율 : 1.0
4회 교차검증의 오차행렬 : 
[[2400    0]
 [   0 7938]] 

[교차검증 : 5회]
5회 교차검증의 정확도 : 1.0
5회 교차검증의 정밀도 : 1.0
5회 교차검증의 재현율 : 1.0
5회 교차검증의 오차행렬 : 
[[2400    0]
 [   0 7938]] 

평균 정확도 1.0
평균 정밀도 1.0
평균 재현율 1.0


In [120]:
Skfold_voting_lr_dt(X_new, y_new)

[교차검증 : 1회]
1회 교차검증의 정확도 : 1.0
1회 교차검증의 정밀도 : 1.0
1회 교차검증의 재현율 : 1.0
1회 교차검증의 오차행렬 : 
[[2399    0]
 [   0 7939]] 

[교차검증 : 2회]
2회 교차검증의 정확도 : 1.0
2회 교차검증의 정밀도 : 1.0
2회 교차검증의 재현율 : 1.0
2회 교차검증의 오차행렬 : 
[[2400    0]
 [   0 7938]] 

[교차검증 : 3회]
3회 교차검증의 정확도 : 1.0
3회 교차검증의 정밀도 : 1.0
3회 교차검증의 재현율 : 1.0
3회 교차검증의 오차행렬 : 
[[2400    0]
 [   0 7938]] 

[교차검증 : 4회]
4회 교차검증의 정확도 : 1.0
4회 교차검증의 정밀도 : 1.0
4회 교차검증의 재현율 : 1.0
4회 교차검증의 오차행렬 : 
[[2400    0]
 [   0 7938]] 

[교차검증 : 5회]
5회 교차검증의 정확도 : 1.0
5회 교차검증의 정밀도 : 1.0
5회 교차검증의 재현율 : 1.0
5회 교차검증의 오차행렬 : 
[[2400    0]
 [   0 7938]] 

평균 정확도 1.0
평균 정밀도 1.0
평균 재현율 1.0
